services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 ustudy_test_task.wsgi:application
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "${PROJECT_PORT}:8000"
    networks:
      - ustudy_test_task_network
      - redis_network
    container_name: ustudy_test_task_web

  db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ustudy_test_task_network
    container_name: ustudy_test_task_db

volumes:
  postgres_data:

networks:
  ustudy_test_task_network:
